version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  receiver:
    build: ./receiver-service
    container_name: receiver
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb+srv://abc:abc.456@cluster0.abc.mongodb.net/SampleDBSuziki
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  listener:
    build: ./listener-service
    container_name: listener
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb+srv://abc:abc.456@cluster0.abc.mongodb.net/SampleDBSuziki
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  mongo_data:
